gts2-common: remove duplicate persist.sys.usb.config property
In Android 12, compiler complains about

error: found duplicate sysprop assignments:
persist.sys.usb.config=mtp
persist.sys.usb.config=mtp,adb
12:01:59 ninja failed with: exit status 1

when making an userdebug image.  When making an eng image,
compiler does not complain.

So we will remove persist.sys.usb.config=mtp to make
compiler happy.